@startuml gaokao

class Province {
    id: int,
    name: string,
    name_pinyin: string
}

class University{
    id: int,
    name: string,
    location: int {foreign key},
    type: enum{综合, 理工, 师范, 农业, 林业}，
    level: Tag
}

class Tag{
    id: int,
    name: enum{985, 211, 双一流}
}

class Department{
    id: int,
    name: string
}

class Major{
    id: int,
    name: string,
    admission_score[n]: int {foreign key},
    student_limit: int
}

class AdmissionScore{
    id: int,
    province: int {foreign key},
    score: int
}

class User{
    id: int,
    name: string,
    location: int {foreign key},
    score: int
}

class WishList{
    id: int,
    user: int {foreign key},
    major: int {foreign key}
}



University "1" *-- "1..*" Department : possess >
University "*" <-- "*" Tag : with >
Department "1" *-- "1..*" Major : has >
Major "1" o.. "1..*" AdmissionScore : contains >
AdmissionScore "1" o.. "1" Province : for >
University "*" ..o "1" Province : in >
User "*" ..o "1" Province : in >
User "1" o.. "*" WishList : possess >
WishList "*" o.. "*" Major : contains >

@enduml